#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: docker run vrpt
  docker:
    docker_api_version: "{{ docker_api_version }}"
    name: vrpt
    image: "{{ vrpt_docker_image }}"
    memory_limit: "{{ vrpt_memory_limit }}"
    restart_policy: always
    state: reloaded
    expose:
      - 5900
    ports:
      - 5900:5900
    command: "{{ vrpt_docker_command }}"
